---
name: "Sceptre GitHub Action"
description: "Runs sceptre commands via GitHub Actions"
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  sceptre_subcommand:
    description: "Sceptre subcommand to execute"
    required: true
  sceptre_version:
    description: "Version of Sceptre to install"
    required: false
    default: "2.5.0"
  sceptre_directory:
    description: "Directory to execute Sceptre commands from"
    required: false
    default: ""
runs:
    using: "docker"
    image: "./Dockerfile"
